apiVersion: v1
kind: Service
metadata:
  name: hello-world-service
  namespace: web  # Specify the namespace
spec:
  selector:
    app: hello-world
  ports:
    - protocol: TCP
      port: 80        # External port to access (changed to 8080)
      targetPort: 80     # Container port (still 80)
  type: LoadBalancer  # This exposes the service externally with an external IP (in AWS)

